from __future__ import annotations

import shutil
from pathlib import Path

from jinja2 import Environment, PackageLoader

import openapi_cli_gen


def generate_package(
    spec: str,
    name: str,
    output_dir: str,
    base_url: str | None = None,
    description: str | None = None,
) -> Path:
    """Generate a CLI package from an OpenAPI spec.

    Args:
        spec: Path or URL to the OpenAPI spec.
        name: Package name (PyPI + CLI binary name). Can contain dashes.
        output_dir: Where to write the package.
        base_url: Optional default base URL for API calls. If None, the
            generated CLI uses the first server from the spec.
        description: Optional PyPI project description. Falls back to a
            generic "CLI for X, generated by openapi-cli-gen" string.
    """
    output = Path(output_dir)

    # Sanitize name for Python module/package directory.
    # PyPI names can have dashes ('qdrant-api-cli') but Python packages can't.
    # So `qdrant-api-cli` becomes module `qdrant_api_cli` but binary stays `qdrant-api-cli`.
    module_name = name.replace("-", "_").replace(" ", "_")

    pkg_dir = output / "src" / module_name
    pkg_dir.mkdir(parents=True, exist_ok=True)

    env = Environment(
        loader=PackageLoader("openapi_cli_gen", "codegen/templates"),
        keep_trailing_newline=True,
    )

    # Derive env var prefix from package name (used for auth token, base URL)
    env_prefix = module_name.upper()

    context = {
        "name": name,
        "module_name": module_name,
        "env_prefix": env_prefix,
        "base_url": base_url,
        "description": description or f"A CLI for the {name} API, generated from its OpenAPI spec",
        "openapi_cli_gen_version": openapi_cli_gen.__version__,
    }

    for template_name, output_path in [
        ("cli.py.jinja2", pkg_dir / "cli.py"),
        ("__init__.py.jinja2", pkg_dir / "__init__.py"),
        ("pyproject.toml.jinja2", output / "pyproject.toml"),
    ]:
        template = env.get_template(template_name)
        output_path.write_text(template.render(**context))

    # README: prefer a hand-crafted README from the monorepo's wrappers/<name>/
    # directory, if it exists. Otherwise render the baseline jinja2 template.
    readme_dest = output / "README.md"
    repo_readme = _find_repo_wrapper_readme(name)
    if repo_readme is not None:
        shutil.copy2(repo_readme, readme_dest)
    else:
        template = env.get_template("README.md.jinja2")
        readme_dest.write_text(template.render(**context))

    # Copy or download the spec file
    spec_dest = pkg_dir / "spec.yaml"
    if spec.startswith(("http://", "https://")):
        import httpx
        resp = httpx.get(spec, follow_redirects=True, timeout=30)
        resp.raise_for_status()
        spec_dest.write_text(resp.text)
    else:
        shutil.copy2(spec, spec_dest)

    return output


def _find_repo_wrapper_readme(name: str) -> Path | None:
    """Look for a hand-crafted README at wrappers/<name>/README.md relative
    to the openapi-cli-gen repo root.

    The repo layout is:
        openapi-cli-gen/
          src/openapi_cli_gen/codegen/generator.py   ← this file
          wrappers/<name>/README.md                   ← target

    When running from an editable install in the repo, we can walk up to find
    `wrappers/`. When running from a site-packages install, no such directory
    exists and we return None (template fallback).
    """
    here = Path(__file__).resolve()
    # generator.py → codegen → openapi_cli_gen → src → <repo root>
    for ancestor in here.parents:
        candidate = ancestor / "wrappers" / name / "README.md"
        if candidate.is_file():
            return candidate
        # Stop walking if we hit the filesystem root
        if ancestor == ancestor.parent:
            break
    return None
